---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kibana.name" . }}-config
  labels:
    app: kibana
data:
  kibana.yml: |-
    server.host: 0.0.0.0

    elasticsearch:
      hosts: ${ELASTICSEARCH_HOSTS}
        # username: ${ELASTICSEARCH_USER}
        # password: ${ELASTICSEARCH_PASSWORD}
---
