---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kibana.name" . }}
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: {{ template "kibana.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - containerPort: 5601
          name: webinterface
        env:
    {{- with .Values.environmentVariables }}
     {{- toYaml . | nindent 10}}
    {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
      volumes:
      - name: config
        configMap:
          name: {{ template "kibana.name" . }}-config
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations: 
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}  
---
