apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fluent-bit.name" . }}

  labels:
    k8s-app: {{ template "fluent-bit.name" . }}
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: {{ template "fluent-bit.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "{{ .Values.backend.es.host }}"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "{{ .Values.backend.es.port }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}        
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: {{ template "fluent-bit.name" . }}-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: {{ template "fluent-bit.name" . }}-config
        configMap:
          name: {{ template "fluent-bit.name" . }}-config
      serviceAccountName: {{ template "fluent-bit.name" . }}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"

