apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "fluent-bit.name" . }}-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fluent-bit.name" . }}-read
subjects:
- kind: ServiceAccount
  name: {{ template "fluent-bit.name" . }}
  namespace: monitoring
